- name: Print debug infomation eg1
  hosts: "{{host}}"
  become: no
  gather_facts: no
  tasks:
    - name: "Statistics CPU Memory Disk Utilization..."
      shell: |
        free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", ($2-$4-$6),$2,($2-$4-$6)*100/$2 }'
      register: out
    - debug: var=out.stdout_lines